### ISSUE TITLE
Build docs for docs.rs with all features

### ISSUE THREAD

**Issue by virtualritz** [termhn/ultraviolet#99]
Currently feature-gated parts of this crate are not documented on `docs.rs`. I.e. one has to clone this repo and build docs themselves via `cargo doc -features f64,int,serde,mint,bytemuck`.

Adding this to `Cargo.toml` should fix this:
```toml
[package.metadata.docs.rs]
features = ["f64", "int", "serde", "mint", "bytemuck"]
```
